export const products = [
    {
        id: 'drop001-cola',
        slug: 'fizzy-cola-bottles',
        emoji: '🥤',
        name: 'FIZZY COLA BOTTLES',
        sub: '1KG TUB · CLASSIC RANGE',
        price: '£6',
        accent: '#c8f535',
        wash: 'rgba(200,245,53,0.04)',
        stripLabel: 'Cola Bottles',
    },
    {
        id: 'drop001-strawberry',
        slug: 'fizzy-strawberries',
        emoji: '🍓',
        name: 'FIZZY STRAWBERRIES',
        sub: '1KG TUB · CLASSIC RANGE',
        price: '£6',
        accent: '#ff2d78',
        wash: 'rgba(255,45,120,0.05)',
        stripLabel: 'Strawberries',
    },
    {
        id: 'drop001-blue-raspberry',
        slug: 'blue-raspberry',
        emoji: '🫐',
        name: 'BLUE RASPBERRY',
        sub: '1KG TUB · SOUR RANGE',
        price: '£6',
        accent: '#1a1aff',
        wash: 'rgba(26,26,255,0.06)',
        stripLabel: 'Blue Raspberry',
    },
    {
        id: 'drop001-rings',
        slug: 'fizzy-rings',
        emoji: '🫧',
        name: 'FIZZY RINGS',
        sub: '1KG TUB · CLASSIC RANGE',
        price: '£6',
        accent: '#ffe600',
        wash: 'rgba(255,230,0,0.05)',
        stripLabel: 'Fizzy Rings',
    },
    {
        id: 'drop001-fishes',
        slug: 'fizzy-big-fishes',
        emoji: '🐟',
        name: 'FIZZY BIG FISHES',
        sub: '1KG TUB · CLASSIC RANGE',
        price: '£6',
        accent: '#c8f535',
        wash: 'rgba(200,245,53,0.04)',
        stripLabel: 'Big Fishes',
    },
];
export const scatterItems = [
    { emoji: '🥤', name: 'Cola Bottles', price: '£6', left: '18%', top: '22%' },
    { emoji: '🍓', name: 'Strawberries', price: '£6', left: '50%', top: '15%' },
    { emoji: '🫐', name: 'Blue Raspberry', price: '£6', left: '80%', top: '25%' },
    { emoji: '🫧', name: 'Fizzy Rings', price: '£6', left: '22%', top: '72%' },
    { emoji: '🐟', name: 'Big Fishes', price: '£6', left: '55%', top: '78%' },
    { emoji: '🟡', name: 'Sour Belts', price: '£4+', left: '80%', top: '65%' },
];
export const SCENES = [
    { start: 0, end: 0.1 },
    { start: 0.1, end: 0.24 },
    { start: 0.24, end: 0.38 },
    { start: 0.38, end: 0.52 },
    { start: 0.52, end: 0.66 },
    { start: 0.66, end: 0.8 },
    { start: 0.8, end: 0.9 },
    { start: 0.9, end: 1.0 },
];
export const SCENE_COUNT = SCENES.length;
export const DROP_META = {
    id: 'drop-001',
    name: 'Drop 001',
    status: 'live',
    freeDeliveryThreshold: 50,
    location: 'Leicestershire',
    yearsEstablished: 20,
};
